### ISSUE TITLE
How to solve the error massage

### ISSUE THREAD

**Issue by tks17g** [shamimshossain/bb8-bluemix#2]
Hello, thank you for your very useful codes.
It is very interesting.

And I want to realize your code.
I have a problem.Could you help me?

I can connect IBM cloud API.

This error message sometimes happen.

-------

**** Start debug info *****
Connected to BB-8
BB-8 is changing color to green to indicate that it is connected
**** End debug info *****
3pfp8c.messaging.internetofthings.ibmcloud.com
Output of ping command
{ sop1: 255,
  sop2: 255,
  mrsp: 0,
  seq: 0,
  dlen: 1,
  data: <Buffer >,
  checksum: 254 }
End of ping data
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/Users/obuko/emotiv/node_modules/mqtt/lib/client.js:673:9)
    at MqttClient._handlePacket (/Users/inobuko/emotiv/node_modules/mqtt/lib/client.js:274:12)
    at process (/Users/aokinobuko/emotiv/node_modules/mqtt/lib/client.js:218:12)
    at Writable.writable._write (/Users/nobuko/emotiv/node_modules/mqtt/lib/client.js:228:5)
    at doWrite (/Users/nobuko/emotiv/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/nobuko/emotiv/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Writable.write (/Users/aokinobuko/emotiv/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at Socket.ondata (_stream_readable.js:646:20)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)

-------------------------

I'm in trouble.Please help me..

Sincerely,
nobuko

**Comment by tks17g** [comment]
sorry, I could solve it.
the cause is "security"

default is "TSL and token authentication" 
I change "TSL option"

thank you.
